# Site settings
title: Crypto Poker
name: "Marc757"
description: "Un sito dedicato al poker e alle criptovalute."
url: "https://marc757.github.io"
baseurl: "/crypto-poker"
locale: "it-IT"

# Site Author
author:
  name   : "Marc757"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Appassionato di poker e criptovalute."
  location: "Italia"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://marc757.github.io/crypto-poker/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://marc757.github.io/crypto-poker/"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: default

# Outputting
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: Europe/Rome

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Include/Exclude
include:
  - _pages

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Search
search: true

# Navigation
main:
  - title: "Home"
    url: /
  - title: "Posts"
    url: /posts/
  - title: "Categorie"
    url: /categories/
  - title: "Tags"
    url: /tags/
  - title: "Chi Siamo"
    url: /about/

# Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://marc757.github.io/crypto-poker/"

# Search
search: true
